import { SkinConditionCategory, ProductRecommendation } from '../types';

export const generatePDF = (analysis: SkinConditionCategory[] | null, recommendations: ProductRecommendation[]) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        alert('Please allow popups to download the report.');
        return;
    }

    const analysisHtml = analysis ? analysis.map(cat => `
        <div class="category">
            <h3>${cat.category}</h3>
            <ul>
                ${cat.conditions.map(c => `
                    <li>
                        <strong>${c.name}</strong> (${Math.round(c.confidence)}%) - ${c.location}
                    </li>
                `).join('')}
            </ul>
        </div>
    `).join('') : '<p>No analysis data available.</p>';

    const recommendationsHtml = recommendations.map(rec => `
        <div class="routine-section">
            <h3>${rec.category}</h3>
            <div class="products-grid">
                ${rec.products.map(p => `
                    <div class="product">
                        <img src="${p.image}" alt="${p.name}" />
                        <div class="product-details">
                            <h4>${p.name}</h4>
                            <p class="price">${p.price}</p>
                            <div class="tags">
                                ${p.tags.map(t => `<span class="tag">${t}</span>`).join('')}
                            </div>
                        </div>
                    </div>
                `).join('')}
            </div>
        </div>
    `).join('');

    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Dermatics AI Report</title>
            <style>
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
                h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
                h2 { color: #1e40af; margin-top: 30px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
                h3 { color: #374151; margin-top: 20px; }
                .category { margin-bottom: 20px; }
                .routine-section { margin-bottom: 30px; }
                .products-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
                .product { border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px; display: flex; gap: 15px; align-items: start; page-break-inside: avoid; }
                .product img { width: 80px; height: 80px; object-fit: cover; border-radius: 6px; }
                .product-details h4 { margin: 0 0 5px 0; font-size: 14px; }
                .price { color: #4b5563; font-size: 13px; margin: 0 0 8px 0; }
                .tags { display: flex; flex-wrap: wrap; gap: 5px; }
                .tag { background: #eff6ff; color: #1d4ed8; padding: 2px 8px; border-radius: 999px; font-size: 10px; font-weight: 600; }
                @media print {
                    body { padding: 0; }
                    .products-grid { display: block; }
                    .product { margin-bottom: 10px; }
                }
            </style>
        </head>
        <body>
            <h1>Dermatics AI Report</h1>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            
            <h2>Analysis Results</h2>
            ${analysisHtml}

            <h2>Recommended Routine</h2>
            ${recommendationsHtml}

            <div style="margin-top: 50px; text-align: center; font-size: 12px; color: #6b7280;">
                <p>Generated by Dermatics AI. This report is for informational purposes only and does not constitute medical advice.</p>
            </div>

            <script>
                window.onload = function() {
                    window.print();
                    // Optional: window.close();
                }
            </script>
        </body>
        </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
};
